### ISSUE TITLE
Update for compatibility with JupyterLab 3

### ISSUE THREAD

**Issue by 3coins** [jupyterlab/jupyterlab-telemetry#23]
### Problem

The current stable version of JupyterLab is 3.x, which is incompatible with the telemetry package. 

### Proposed Solution

Update dependencies and code to make it compatible with JupyterLab 3.

- [x] Update jupyterlab dependencies to 3.3.x
- [x] Replace phosphor dependencies with lumino
- [x] Update typescript to 4.8.1
- [x] Update dev dependencies
- [x] Update code for successful build

**Comment by 3coins** [comment]
@yuvipanda @Zsailer @blink1073 
I am planning to work on this issue, but wanted to understand the amount of effort required for this. Can one of you please help evaluate this? 
Other than upgrading the dependencies and JS code, is there any server extension code that would change significantly here? Would it be better to start with an empty cookie cutter pre-built extension and move code from this package? 

Thanks for your help.

**Comment by yuvipanda** [comment]
https://github.com/jupyter-server/jupyter_server/pull/364 might be relevant?

**Comment by fcollonval** [comment]
@3coins see official documentation to [migrate lab extension](https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html#upgrading-library-versions-using-the-upgrade-script) and that one for [the server part](https://jupyter-server.readthedocs.io/en/latest/developers/extensions.html#migrating-an-extension-to-use-jupyter-server).

In popular extensions, you will be able to find PR to migrate to JLab3 like [that one](https://github.com/jupyterlab-contrib/jupyter-archive/pull/43) - that has a similar size as this one.

**Comment by fcollonval** [comment]
> Update typescript to 4.8.1

I advice updating to the same version of JupyterLab and not to the latest.

**Comment by 3coins** [comment]
@yuvipanda 
Thanks for providing that info. 

It seems like [#501](https://github.com/jupyter-server/jupyter_server/pull/501) is still in draft mode, and there hasn't been an update from the author since May 2021. I have 2 options here:
1. Wait for [#501](https://github.com/jupyter-server/jupyter_server/pull/501) to be merged. In this case, this telemetry package won't need any server side components.
2. Go ahead and update the telemetry package, remove the server extension when [#501](https://github.com/jupyter-server/jupyter_server/pull/501) is merged.

My inclination is towards going with `#2`, as my team is upgrading to JLab 3, and need this package to work with JLab 3. However, I will bring this up at this week's server meeting and go forward from there.

**Comment by yuvipanda** [comment]
@3coins (2) sounds good to me!

**Comment by Zsailer** [comment]
Yeah, I agree with (2) right now, also. @3coins, I'm happy to meet this week sometime to discuss futures plans for this repo, if you'd like. We can also discuss this at the jupyter-server meeting.
